/*
------------------------------
Clown Gang
------------------------------
*/

/datum/skills/clown
	name = "Apprentice"
	skills = list(
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
	)

/datum/skills/clown/spec
	name = "Jester"
	skills = list(
		SKILL_LEADERSHIP = SKILL_LEAD_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_EXPERT,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
	)
